### ISSUE TITLE
License of the dataset

### ISSUE THREAD

**Issue by najmehs** [MaxyLee/3AM#1]
Can you please provide the license for this dataset?
Thanks!

**Comment by MaxyLee** [comment]
Hello, thank you for your inquiry regarding the license for our dataset. We appreciate your attention and engagement with our work. The license for our dataset is the MIT License. This license allows users to freely use, modify, and distribute the software as long as they include the original copyright and license notice. If you have any further questions or need additional information, please don't hesitate to ask.
