### ISSUE TITLE
Images Missing

### ISSUE THREAD

**Issue by iz2late** [MaxyLee/3AM#2]
There are only 456 images in the link you provide. Could you please advise how to access the full images?

**Comment by MaxyLee** [comment]
Hello, thank you for your inquiry. The missing images will be uploaded as soon as possible.

**Comment by MaxyLee** [comment]
Hello. The images are available at [this link](https://uofmacau-my.sharepoint.com/:f:/g/personal/yc27434_um_edu_mo/EvdxzWiEiO9PhS0Fdyc7oecBIlG5N-WD2D1QCB4jLJ9r6Q?e=87Omen). 
Thank you again for your inquiry. Please feel free to contact us if you have any other questions.

**Comment by iz2late** [comment]
> Hello. The images are available at [this link](https://uofmacau-my.sharepoint.com/:f:/g/personal/yc27434_um_edu_mo/EvdxzWiEiO9PhS0Fdyc7oecBIlG5N-WD2D1QCB4jLJ9r6Q?e=87Omen). Thank you again for your inquiry. Please feel free to contact us if you have any other questions.

Thank you so much for the update! Unfortunately, OneDrive only supports downloading 10,000 files at a time, but there are around 25,000 images, which causes download errors.

I know this might be a bit of an unreasonable request, but it would be much more convenient if you could zip the images into a single compressed file. This way, it would be easier to download.

**Comment by MaxyLee** [comment]
> > Hello. The images are available at [this link](https://uofmacau-my.sharepoint.com/:f:/g/personal/yc27434_um_edu_mo/EvdxzWiEiO9PhS0Fdyc7oecBIlG5N-WD2D1QCB4jLJ9r6Q?e=87Omen). Thank you again for your inquiry. Please feel free to contact us if you have any other questions.
> 
> Thank you so much for the update! Unfortunately, OneDrive only supports downloading 10,000 files at a time, but there are around 25,000 images, which causes download errors.
> 
> I know this might be a bit of an unreasonable request, but it would be much more convenient if you could zip the images into a single compressed file. This way, it would be easier to download.

Hello. I have reuploaded the images as a compressed file. Please check out [this link](https://uofmacau-my.sharepoint.com/:f:/g/personal/yc27434_um_edu_mo/EvdxzWiEiO9PhS0Fdyc7oecBIlG5N-WD2D1QCB4jLJ9r6Q?e=hOLhla).

**Comment by iz2late** [comment]
> > > Hello. The images are available at [this link](https://uofmacau-my.sharepoint.com/:f:/g/personal/yc27434_um_edu_mo/EvdxzWiEiO9PhS0Fdyc7oecBIlG5N-WD2D1QCB4jLJ9r6Q?e=87Omen). Thank you again for your inquiry. Please feel free to contact us if you have any other questions.
> > 
> > 
> > Thank you so much for the update! Unfortunately, OneDrive only supports downloading 10,000 files at a time, but there are around 25,000 images, which causes download errors.
> > I know this might be a bit of an unreasonable request, but it would be much more convenient if you could zip the images into a single compressed file. This way, it would be easier to download.
> 
> Hello. I have reuploaded the images as a compressed file. Please check out [this link](https://uofmacau-my.sharepoint.com/:f:/g/personal/yc27434_um_edu_mo/EvdxzWiEiO9PhS0Fdyc7oecBIlG5N-WD2D1QCB4jLJ9r6Q?e=hOLhla).

This is awesome! Thank you so much for your prompt help!
